services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: food_delivery
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./HTML:/usr/local/tomcat/webapps/ROOT/HTML
      - ./JS:/usr/local/tomcat/webapps/ROOT/JS
      - ./CSS:/usr/local/tomcat/webapps/ROOT/CSS
      - ./IMAGES:/usr/local/tomcat/webapps/ROOT/IMAGES
      - ./WEB-INF:/usr/local/tomcat/webapps/ROOT/WEB-INF

  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
